### ISSUE TITLE
./configure gives an error on Ubuntu 10.10 (x64)

### ISSUE THREAD

**Issue by discofever** [kanaka/libvncserver#1]
```
    ./configure: line 21755: syntax error near unexpected token `GNUTLS,'
    ./configure: line 21755: `PKG_CHECK_MODULES(GNUTLS, gnutls >= 2.4.0, , with_client_tls=no)'
```

I have all packages installed
libgnutls-dev 2.8.6-1
libgnutls26 2.8.6-1
gnutls-bin 2.8.6-1

**Comment by kanaka** [comment]
Can you pull down the latest tree of libvncserver from upstream and see if it builds successfully on 10.10. I don't have easy access to a 10.10 system to replicate your problem. If the upstream version builds for you then I will pull it down and see if I can figure out the difference. If it doesn't build and you run into the same problem, then it's probably something about your installation, or it's a bug that should be filed upstream.

git://libvncserver.git.sourceforge.net/gitroot/libvncserver/libvncserver

Thanks. I'll leave the bug open until you post back results.

**Comment by discofever** [comment]
Ok, pulled upstream. Same error. And no clue on what's wrong. Maybe a syntax error ? but looks ok to me.

**Comment by discofever** [comment]
Ok fixed, was missing pkg-config package.

**Comment by tbtlr** [comment]
How did you solve the issue in detail? I've run into the same on Mac OSX 10.6.

**Comment by kanaka** [comment]
tobeytailor, according to discofever the error he was seeing was because the pkg-config package was not installed on his system. pkg-config provides the PKG_CHECK_MODULES m4 autoconf macro (http://www.flameeyes.eu/autotools-mythbuster/pkgconfig/pkg_check_modules.html).

Are you seeing exactly the same error as discofever? Do you have pkg-config installed? 

Can you try running the following:

```
pkg-config gnutls --libs
```

You should get output similar to:

```
-lgnutls
```

**Comment by tbtlr** [comment]
Yes, I see the same error as discofever. But I have pkg-config installed. Output of the command listed above is:

-L/usr/local/Cellar/gnutls/2.10.5/lib -lgnutls

**Comment by kanaka** [comment]
The PKG_CHECK_MODULES m4 macro comes from the pkg.m4 file. On my system, the pkg-config package installs it to /usr/share/aclocal/pkg.m4.

My guess is that when autoconf is run (by ./autogen.sh) it's not finding the pkg.m4 file so it leaves the PKG_CHECK_MODULES macro unexpanded in the configure script.

Probably the best thing is to try and figure out why autoconf isn't finding pkg.m4. 

Alternately, you might be able to re-run autoconf with the -I (or -B) option to point to the path where pkg-config installed pkg.m4 (or add the path to the autoconf call in autogen.sh and run that again).

**Comment by kanaka** [comment]
Actually, aclocal is the command that pulls in the *.m4 files. I notice the autogen.sh has a variable used to add to the aclocal command line.

So this might work:

```
ACLOCAL_FLAGS="-I /path/to/m4/dir" ./autogen.sh
```

Substitute in the directory containing pkg.m4 for that path.

**Comment by kanaka** [comment]
Another hint: if aclocal pulls in the pkg.m4 file you should see PKG_CHECK_MODULES defined in the aclocal.m4 file generated at the top of the libvncserver directory after aclocal (i.e. autogen.sh) runs.

**Comment by tbtlr** [comment]
Yes, setting the ACLOCAL_FLAGS environment variable works for me. Thanks a lot!

**Comment by kanaka** [comment]
Awesome!

**Comment by zhuyjgh** [comment]
kanaka,Thanks! for me    ACLOCAL_FLAGS="-I /usr/share/aclocal" ./autogen.sh    worked!! 
I find my pkg.m4 here:/usr/share/aclocal.

**Comment by dscho** [comment]
Please note that @kanaka is not a maintainer of LibVNCServer I just added an official GitHub repository for the project: https://github.com/LibVNC/libvncserver. Please consider opening the pull request there.
