### ISSUE TITLE
Compiling with Android Studio 2.3

### ISSUE THREAD

**Issue by pedroelisio** [kanaka/libvncserver#8]
Hi, maybe you can help me.....I am compiling your project with Android Studio 2.3 in a Windows 8 machine but the following error appears:

![image](https://cloud.githubusercontent.com/assets/3877898/23853954/06366662-07e7-11e7-9fcb-07551f2a0695.png)

What dependencies are missing?
Best Regards,
Pedro Elísio

**Comment by kanaka** [comment]
@pedroelisio this is an old fork that I used to submit a pull request to the original. You really want https://github.com/LibVNC/libvncserver

**Comment by pedroelisio** [comment]
It is not clear to me about how to build android app using your lib.
Do you know any android app that uses your lib?
Best Regards,
Pedro Elisio

Joel Martin <notifications@github.com> escreveu no dia segunda, 13/03/2017
às 17:18:

**Comment by kanaka** [comment]
@pedroelisio as I said, this is not the real libvncserver project. It's a temporary copy that I made years ago for a single purpose. I'll probably delete it soon. If you need libvncserver assistance please contact the real project. Thanks!
